### ISSUE TITLE
Review - Reproducibility/Best practice

### ISSUE THREAD

**Issue by cvitolo** [esowc/ml_flood#31]
- Please make sure all your notebooks contain fully reproducible examples. Non-reproducible procedures will not be acceptable.

- It would be great to add small sample datasets to allow readers to test notebooks and functions. This should be fairly simple, especially where you process data for a fixed grid point.

- Please explain how data are supposed to be stored (e.g. folder structure, file naming convention, etc)

- Please remove any inconsistencies, for instance, in **008_test_linear_model** ‘surrounding’ should probably be ‘local_region’, also in **011_explaining_showcasing_the_transportmodel** there is a plot with wrong labels

- The notebooks need tidying up and, if possible, please run spelling/linter checks on them.

- Functions in your python folder are not fully documented and there are no unit tests. Is this something you plan to work on by the end of the programme?

**Comment by lkugler** [comment]
- The small sample-dataset is now also contained in the git repo. The folder structure is/will be in the notebooks. 

- Spelling/Linter checks:
Is it sufficient to run them on code in .py files only (in the python/aux directory)? It does not work within 5 minutes in jupyter and I don't know how long it will take to get it to work.

- Tests
Now that we have a sample dataset that is the same for every user, we can implement tests for a few preprocessing/reshaping routines as most can go wrong here. Given the amount of open issues I fear only a few can be implemented, e.g. `get_mask_of_basin` and `preprocess_reshape_flowmodel`.

**Comment by lkugler** [comment]
Apart from unit tests, which were started in [tests.py](https://github.com/esowc/ml_flood/blob/master/python/aux/tests.py), all points should be fixed now.
