### ISSUE TITLE
Review - ML-techniques

### ISSUE THREAD

**Issue by jwagemann** [esowc/ml_flood#35]
- By the end of the programme, please provide a comparison of the different models (maybe in a summary table?), list advantages and disadvantages, comment on complexity/usability, propose future work, e.g. are you planning to explore LSTM (https://arxiv.org/pdf/1907.08456.pdf) in the future?

**Comment by seblehner** [comment]
Although the project is already succesfully finished, for completeness sake here is additional information: Tables with evaluation metrics, plots and comments are shown in the presentation for the final ESoWC19 day and can be found here: [final talk](https://github.com/MATEHIW-project/matehiw-project.github.io/blob/master/assets/ESoWC2019_ml_flood_final_pres.pdf).
