### ISSUE TITLE
Review - Feature engineering

### ISSUE THREAD

**Issue by jwagemann** [esowc/ml_flood#36]
- Could you please comment on how you prepare features to input into the model (e.g. reshaping the original 3D array, generate derived/shifted variables, etc.). Some info on shifted variables is available in 008_test_linear_model but it is unclear why you choose to shift by 10 time steps, please justify your choice.

- Do you need to do different types of engineering for different models?

**Comment by lkugler** [comment]
Feature engineering from a "reshaping" point of view is answered in [2_preprocessing/2.04_reshape_for_training.ipynb](https://github.com/esowc/ml_flood/blob/master/notebooks/2_preprocessing/2.04_reshape_for_training.ipynb); the reshaping differs of course between forecasting one-dimensional and multi-dimensional (multiday) forecasts.
Feature engineering from a model architectural point of view is answered in 2.02 and  2.03 ([2_preprocessing/](https://github.com/esowc/ml_flood/blob/master/notebooks/2_preprocessing))
