### ISSUE TITLE
Review - CDO-based methods

### ISSUE THREAD

**Issue by jwagemann** [esowc/ml_flood#37]
- We noticed you have developed your own cdo-based methods (004_preprocessing_with_cdo.ipynb), which are wrappers around system calls to cdo. Can you please explain the advantage? Is the cdo python package (https://pypi.org/project/cdo/) lacking functionalities? If so, are you considering contributing to the package with your methods?

**Comment by lkugler** [comment]
We were used to using cdo as cmd-line tool and not aware of the cdo python package. Switching to the cdo python-package is a goal but I think currently there are more pressing issues than this one.

**Comment by lkugler** [comment]
Added reference to CDO-python in commit 629b8db552045053c54f4c893fd8312444fded2d for https://github.com/esowc/ml_flood/blob/master/notebooks/1_data_download_analysis_visualization/1.04_preprocessing_with_cdo.ipynb
